export const SET_DATA = 'SET_DATA'
export const ADD_SUBJECT = 'ADD_SUBJECT'
export const DELETE_SUBJECT = 'DELETE_SUBJECT'
export const ADD_CLASS = 'ADD_CLASS'
export const DELETE_CLASS = 'DELETE_CLASS'
export const ADD_VIEW = 'ADD_VIEW'
export const REMOVE_VIEW = 'REMOVE_VIEW'